[package]
name = "simple_api_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
serde = "1"
serde_derive = "1"
serde_json = "1"
reqwest = {version = "0.12.9", features = ["stream"]}
bytes = "1"
futures = "0.3"