[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.4.1", features = ["full"] }
futures = "0.3.30"
tokio = { version = "1", features = ["full"] }
hyper-util = { version = "0.1.6", features = ["full"] }